import subprocess
import time
from typing import Optional
import pyperclip


class ClipboardPaster:
    def __init__(self, auto_paste: bool = True, restore_clipboard: bool = False, use_clipboard: bool = True):
        self.auto_paste = auto_paste
        self.restore_clipboard = restore_clipboard
        self.use_clipboard = use_clipboard

    def paste(self, text: str) -> bool:
        if not text or not text.strip():
            return False

        if not self.use_clipboard:
            # Type directly without touching clipboard at all
            return self._simulate_direct_typing(text)

        old_clipboard: Optional[str] = None
        if self.restore_clipboard:
            try:
                old_clipboard = pyperclip.paste()
            except Exception:
                old_clipboard = None

        try:
            # 1. Set text to system clipboard with Transient & Concealed types so clipboard managers ignore it
            self._copy_to_clipboard_transient(text)
            time.sleep(0.05)  # Allow clipboard buffer to sync on macOS
        except Exception as e:
             print(f"Error copying text to clipboard: {e}")
             return False

        if not self.auto_paste:
            return True

        # 2. Simulate Cmd + V keystroke using AppleScript (System Events)
        pasted = self._simulate_cmd_v()
        if not pasted:
            # Fallback to pynput if osascript fails
            pasted = self._simulate_cmd_v_pynput()

        # 3. Optionally restore old clipboard content after a delay
        if self.restore_clipboard and old_clipboard is not None:
            time.sleep(0.3)  # Give target app time to process the paste event
            try:
                pyperclip.copy(old_clipboard)
            except Exception:
                pass

        return pasted

    def _copy_to_clipboard_transient(self, text: str):
        """Copy to macOS NSPasteboard with Transient and Concealed types so clipboard managers ignore it."""
        import sys
        if sys.platform != "darwin":
            pyperclip.copy(text)
            return
        try:
            # Run in a clean subprocess to ensure main-thread AppKit execution and avoid ARM-64 background thread traps
            script = """
import sys, ctypes, ctypes.util
text = sys.stdin.read()
ctypes.cdll.LoadLibrary("/System/Library/Frameworks/AppKit.framework/AppKit")
objc = ctypes.cdll.LoadLibrary(ctypes.util.find_library("objc"))
get_class = ctypes.CFUNCTYPE(ctypes.c_void_p, ctypes.c_char_p)(("objc_getClass", objc))
register_sel = ctypes.CFUNCTYPE(ctypes.c_void_p, ctypes.c_char_p)(("sel_registerName", objc))
msg_send_ptr = ctypes.CFUNCTYPE(ctypes.c_void_p, ctypes.c_void_p, ctypes.c_void_p)(("objc_msgSend", objc))
msg_send_void = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_void_p)(("objc_msgSend", objc))
msg_send_bool = ctypes.CFUNCTYPE(ctypes.c_bool, ctypes.c_void_p, ctypes.c_void_p, ctypes.c_void_p, ctypes.c_void_p)(("objc_msgSend", objc))
msg_send_id = ctypes.CFUNCTYPE(ctypes.c_void_p, ctypes.c_void_p, ctypes.c_void_p, ctypes.c_char_p)(("objc_msgSend", objc))

cls_pb = get_class(b"NSPasteboard")
pb = msg_send_ptr(cls_pb, register_sel(b"generalPasteboard"))
msg_send_void(pb, register_sel(b"clearContents"))

cls_str = get_class(b"NSString")
str_utf8 = register_sel(b"stringWithUTF8String:")
text_ns = msg_send_id(cls_str, str_utf8, text.encode("utf-8"))

sel_set = register_sel(b"setString:forType:")
msg_send_bool(pb, sel_set, text_ns, msg_send_id(cls_str, str_utf8, b"public.utf8-plain-text"))
msg_send_bool(pb, sel_set, msg_send_id(cls_str, str_utf8, b""), msg_send_id(cls_str, str_utf8, b"org.nspasteboard.TransientType"))
msg_send_bool(pb, sel_set, msg_send_id(cls_str, str_utf8, b""), msg_send_id(cls_str, str_utf8, b"org.nspasteboard.ConcealedType"))
msg_send_bool(pb, sel_set, msg_send_id(cls_str, str_utf8, b""), msg_send_id(cls_str, str_utf8, b"org.nspasteboard.AutoGeneratedType"))
"""
            import os
            if getattr(sys, 'frozen', False):
                python_exe = "/usr/bin/python3"
                if not os.path.exists(python_exe):
                    pyperclip.copy(text)
                    return
            else:
                python_exe = sys.executable

            res = subprocess.run([python_exe, "-c", script], input=text, text=True, capture_output=True, check=False)
            if res.returncode != 0:
                print(f"[Clipboard] Transient subprocess warning: {res.stderr.strip()}")
                pyperclip.copy(text)
        except Exception as e:
            print(f"[Clipboard] Transient pasteboard setting failed, falling back to pyperclip: {e}")
            pyperclip.copy(text)

    def _simulate_direct_typing(self, text: str) -> bool:
        """Type string character by character without touching system clipboard using AppleScript."""
        try:
            # Escape backslashes and double quotes for AppleScript string
            escaped_text = text.replace('\\', '\\\\').replace('"', '\\"')
            script = f'tell application "System Events" to keystroke "{escaped_text}"'
            result = subprocess.run(
                ["osascript", "-e", script],
                capture_output=True,
                text=True,
                check=False
            )
            if result.returncode != 0:
                print(f"osascript direct typing warning: {result.stderr.strip()}")
                return self._simulate_direct_typing_pynput(text)
            return True
        except Exception as e:
            print(f"Error running direct typing osascript: {e}")
            return self._simulate_direct_typing_pynput(text)

    def _simulate_direct_typing_pynput(self, text: str) -> bool:
        try:
            from pynput.keyboard import Controller
            keyboard = Controller()
            keyboard.type(text)
            return True
        except Exception as e:
            print(f"Error running direct typing pynput fallback: {e}")
            return False

    def _simulate_cmd_v(self) -> bool:
        try:
            script = 'tell application "System Events" to keystroke "v" using command down'
            result = subprocess.run(
                ["osascript", "-e", script],
                capture_output=True,
                text=True,
                check=False
            )
            if result.returncode != 0:
                print(f"osascript paste warning: {result.stderr.strip()}")
                return False
            return True
        except Exception as e:
            print(f"Error running osascript Cmd+V: {e}")
            return False

    def _simulate_cmd_v_pynput(self) -> bool:
        try:
            from pynput.keyboard import Controller, Key
            keyboard = Controller()
            with keyboard.pressed(Key.cmd):
                keyboard.press('v')
                keyboard.release('v')
            return True
        except Exception as e:
            print(f"Error running pynput Cmd+V fallback: {e}")
            return False
